version: '3.8'

services:
  db:
    image: postgres:15
    container_name: storeroom_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: storeroom_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: storeroom_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/storeroom_db
    depends_on:
      - db

volumes:
  postgres_data:
